apiVersion: v1 
kind: Pod 
metadata: 
  name: gpu-pod 
spec: 
  restartPolicy: Never 
  containers: 
   - name: cuda-container 
     image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2 
     resources: 
       limits: 
         nvidia.com/gpu: 1 # requesting 1 GPU 
  tolerations: 
    - key: "dedicated"
      operator: "Equal"
      value: "gpuGroup" 
      effect: "NoSchedule"

# Tolerations:                 dedicated=gpuGroup:NoSchedule
#                              node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
#                              node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
#                              nvidia.com/gpu:NoSchedule op=Exists